# Simplified Supervisor Configuration for LangGraph
version: "0.6.6"

# Metadata
metadata:
  name: "RealEstate_Assistant"
  description: "부동산 전문 AI 어시스턴트"
  language: "ko"
  domain: "real_estate"
  created_by: "Holmes & Yangz System"
  created_date: "2025-01-10"

# Query Analyzer
query_analyzer:
  intent_detection:
    - intent: "information_search"
      description: "정보 검색 및 조회"
      keywords: ["찾아", "알려", "검색", "조회", "확인"]
      examples: ["강남구 아파트 시세를 찾아줘"]
      confidence_threshold: 0.7
    
    - intent: "calculation"
      description: "계산 및 분석"
      keywords: ["계산", "분석", "비교", "평가", "얼마"]
      examples: ["대출 가능 금액 계산해줘"]
      confidence_threshold: 0.75
  
  entity_extraction:
    location:
      patterns: ["\\b\\w+구\\b", "\\b\\w+동\\b"]
      examples: ["강남구", "서초동"]
    price:
      patterns: ["\\d+억", "\\d+천", "\\d+만원"]
      examples: ["5억", "3천만원"]

# Agents
agents:
  - id: "price_search_agent"
    name: "시세 검색 전문가"
    description: "부동산 시세 정보 검색 및 분석"
    capabilities:
      - "실거래가 조회"
      - "전세/월세 시세 분석"
      - "시세 동향 분석"
      - "지역별 가격 비교"
    trigger_conditions:
      intents: ["information_search", "calculation"]
      entities: ["price", "property_type", "location"]
      keywords: ["시세", "가격", "매매가", "전세", "월세", "얼마"]
    tools:
      - "search_real_estate_price"
      - "analyze_price_trend"
      - "compare_prices"
    max_execution_time: 30
    retry_policy:
      max_retries: 3
      backoff: "exponential"
      initial_delay: 1.0
    priority: 1

  - id: "finance_agent"
    name: "자본 관리 전문가"
    description: "대출, 예산, 세금 등 부동산 금융 상담"
    capabilities:
      - "대출 한도 계산"
      - "상환액 시뮬레이션"
      - "세금 계산"
      - "투자 수익률 분석"
    trigger_conditions:
      intents: ["calculation", "consultation"]
      entities: ["loan", "budget", "tax"]
      keywords: ["대출", "예산", "자금", "이자", "DTI", "LTV"]
    tools:
      - "calculate_loan_limit"
      - "simulate_monthly_payment"
      - "calculate_taxes"
    max_execution_time: 45
    retry_policy:
      max_retries: 3
      backoff: "exponential"
      initial_delay: 1.0
    priority: 2

  - id: "location_agent"
    name: "입지 분석 전문가"
    description: "위치 기반 인프라, 교통, 학군 분석"
    capabilities:
      - "교통 접근성 평가"
      - "학군 정보 제공"
      - "편의시설 분석"
      - "주변 환경 평가"
    trigger_conditions:
      intents: ["information_search", "recommendation"]
      entities: ["location", "infrastructure"]
      keywords: ["역세권", "학군", "교통", "지하철", "버스", "마트", "병원"]
    tools:
      - "search_nearby_facilities"
      - "evaluate_accessibility"
      - "analyze_school_district"
    max_execution_time: 30
    retry_policy:
      max_retries: 2
      backoff: "linear"
      initial_delay: 1.0
    priority: 3

  - id: "legal_agent"
    name: "법률 자문 전문가"
    description: "부동산 법률, 계약, 세금, 규제 상담"
    capabilities:
      - "계약서 검토"
      - "세금 안내"
      - "법적 요건 확인"
      - "분쟁 해결 안내"
    trigger_conditions:
      intents: ["information_search", "consultation"]
      entities: ["law", "contract", "tax"]
      keywords: ["계약", "법률", "세금", "취득세", "양도세", "등기", "임대차"]
    tools:
      - "explain_contract_terms"
      - "calculate_acquisition_tax"
      - "check_legal_requirements"
    max_execution_time: 40
    retry_policy:
      max_retries: 2
      backoff: "constant"
      initial_delay: 1.0
    priority: 4

# Routing
routing:
  strategy: "hybrid"
  rules:
    - name: "복합 질의 처리"
      description: "여러 도메인 질의 병렬 처리"
      condition: "multiple_intents_detected"
      action: "parallel_execution"
      max_agents: 3
    
    - name: "단순 질의 처리"
      description: "단일 도메인 직접 라우팅"
      condition: "single_intent_detected"
      action: "direct_routing"
      min_confidence: 0.7
  
  parallel_execution:
    enabled: true
    max_concurrent_agents: 3
    timeout: 60
    merge_strategy: "confidence_weighted"
  
  sequential_execution:
    enabled: true
    order: "by_dependency"
    pass_results: true

# Execution Policies
execution_policies:
  error_handling:
    on_agent_failure:
      strategy: "fallback"
      max_retries: 3
      retry_delay: 2
    on_timeout:
      strategy: "partial_result"
      extension_time: 30
    on_rate_limit:
      strategy: "exponential_backoff"
      initial_delay: 1
      max_delay: 60
      max_attempts: 5
  
  retry_policies:
    default:
      max_retries: 3
      backoff: "exponential"
      initial_delay: 1
      max_delay: 30

# Response Generation
response_generation:
  format: "structured"
  include_confidence: true
  include_sources: true
  include_execution_time: false
  max_length: 2000
  templates:
    greeting: "안녕하세요! 부동산 AI 어시스턴트입니다."
    clarification: "좀 더 구체적으로 말씀해 주시겠어요?"
    processing: "{query}에 대해 분석 중입니다..."
    result: "[{agent_name}의 분석 결과]\n{content}"
    error: "죄송합니다. 요청 처리 중 문제가 발생했습니다."
    multi_agent_result: "종합 분석 결과입니다:\n{combined_results}"

# Monitoring
monitoring:
  metrics:
    - "response_time"
    - "error_rate"
    - "token_usage"
  logging:
    level: "INFO"
    include_user_query: true
    include_agent_decisions: true
    include_tool_calls: true
  tracing:
    enabled: true
    provider: "langsmith"
    sample_rate: 1.0

# Optimization
optimization:
  caching:
    enabled: true
    provider: "memory"
    ttl: 3600
    max_cache_size: "1GB"
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    requests_per_hour: 1000
  batching:
    enabled: false
    max_batch_size: 10
    batch_timeout: 5
  model_settings:
    default_model: "gpt-4"
    temperature: 0.7
    max_tokens: 2000
    streaming: true
  model_config:
    default_model: "gpt-4"
    temperature: 0.7
    max_tokens: 2000
    streaming: true

# Security
security:
  input_validation:
    enabled: true
    max_query_length: 1000
    sanitize_html: true
    block_patterns:
      - "(?i)(drop|delete|truncate)\\s+table"
      - "(?i)<script.*?</script>"
  api_keys:
    rotation_enabled: true
    rotation_interval: 30
    encryption: "AES256"
  authentication:
    required: false
    method: "jwt"
    session_timeout: 3600